#!/usr/bin/env python3
"""
europe-train 多语言首页翻译脚本
翻译首页内容（标题、描述、按钮等）为对应语言
"""

import os
import json

BASE_DIR = "/root/.openclaw/workspace/europe-train"

# 翻译映射表
TRANSLATIONS = {
    'de': {
        'title': 'Europe Train | Europäische Bahn-Reiseguides - Routen, Tickets, Pässe',
        'description': 'Der vollständige Guide für Bahnreisen in Europa. Finde Routen, vergleiche Tickets und entdecke die besten Pässe.',
        'hero_title': 'Europa mit dem Zug entdecken',
        'hero_desc': 'Der vollständige Guide für Bahnreisen in Europa. Finde Routen, vergleiche Tickets und entdecke die besten Pässe.',
        'search_placeholder': 'Suche nach Zielen, Routen oder Zugtypen...',
        'search_button': 'Suchen',
        'features_title': 'Warum Bahnreisen?',
        'feature_eco': 'Umweltfreundlich',
        'feature_eco_desc': 'Züge produzieren 90% weniger CO₂ als Flugzeuge. Entdecke Europa nachhaltig.',
        'feature_comfort': 'Komfort',
        'feature_comfort_desc': 'Geräumige Sitze, Speisewagen, kostenloses WLAN. Genieße die Reise.',
        'feature_city': 'Direkt ins Zentrum',
        'feature_city_desc': 'Keine Flughafentransfers. Direkt ins Zentrum jeder europäischen Stadt.',
        'feature_price': 'Preis-Leistung',
        'feature_price_desc': 'Pässe und Frühbucherrabatte sparen Geld. Für jedes Budget.',
        'stats_title': 'Europäische Bahnreise Daten',
        'stats_countries': 'Länder abgedeckt',
        'stats_network': 'km Schienennetz',
        'stats_trains': 'Züge pro Tag',
        'stats_co2': 'weniger CO₂ als Flug',
        'articles_title': 'Neueste Reiseguides',
        'articles_desc': 'Tiefgehende Vergleiche, Zugerlebnisse, Expertenwissen für deine perfekte europäische Bahnreise',
        'routes_title': 'Beliebte Strecken',
        'routes_link': 'Alle Strecken →',
        'passes_title': 'Eurail & Interrail Pässe',
        'passes_desc': 'Flexibel durch Europa reisen mit einem Pass. 33 Länder, ein Ticket.',
        'passes_link': 'Pässe vergleichen →',
        'cta_title': 'Bereit für deine europäische Bahnreise?',
        'cta_desc': 'Finde die besten Tickets, Routen und Pässe für deine perfekte Reise.',
        'cta_button': 'Jetzt planen',
        'footer_desc': 'Der vollständige Guide für Bahnreisen in Europa.',
        'footer_routes': 'Beliebte Strecken',
        'footer_tickets': 'Tickets',
        'footer_passes': 'Pässe',
        'footer_guides': 'Reiseguides',
        'footer_contact': 'Kontakt',
        'footer_copyright': '© 2025 Europe Train. Alle Rechte vorbehalten.',
    },
    'fr': {
        'title': 'Europe Train | Guides de voyage en train en Europe - Itinéraires, billets, pass',
        'description': 'Le guide complet pour voyager en train en Europe. Trouvez des itinéraires, comparez les billets et découvrez les meilleurs pass.',
        'hero_title': "Découvrez l'Europe en train",
        'hero_desc': 'Le guide complet pour voyager en train en Europe. Trouvez des itinéraires, comparez les billets et découvrez les meilleurs pass.',
        'search_placeholder': 'Rechercher des destinations, itinéraires ou types de trains...',
        'search_button': 'Rechercher',
        'features_title': 'Pourquoi voyager en train ?',
        'feature_eco': 'Écologique',
        'feature_eco_desc': 'Les trains émettent 90% moins de CO₂ que les avions. Explorez Europe durablement.',
        'feature_comfort': 'Confort',
        'feature_comfort_desc': 'Sièges spacieux, wagon-restaurant, WiFi gratuit. Profitez du voyage.',
        'feature_city': 'Directement en centre-ville',
        'feature_city_desc': "Pas de transferts aéroport. Directement au centre de chaque ville européenne.",
        'feature_price': 'Rapport qualité-prix',
        'feature_price_desc': 'Les pass et réductions early bird font économiser de l\'argent. Pour tous les budgets.',
        'stats_title': 'Données sur les voyages en train en Europe',
        'stats_countries': 'Pays couverts',
        'stats_network': 'km de réseau ferroviaire',
        'stats_trains': 'Trains par jour',
        'stats_co2': 'moins de CO₂ que l\'avion',
        'articles_title': 'Derniers guides de voyage',
        'articles_desc': 'Comparaisons approfondies, expériences de train, expertise pour votre voyage en train parfait en Europe',
        'routes_title': 'Itinéraires populaires',
        'routes_link': 'Tous les itinéraires →',
        'passes_title': 'Pass Eurail & Interrail',
        'passes_desc': 'Voyagez flexiblement à travers Europe avec un pass. 33 pays, un billet.',
        'passes_link': 'Comparer les pass →',
        'cta_title': 'Prêt pour votre voyage en train en Europe ?',
        'cta_desc': 'Trouvez les meilleurs billets, itinéraires et pass pour votre voyage parfait.',
        'cta_button': 'Planifier maintenant',
        'footer_desc': 'Le guide complet pour voyager en train en Europe.',
        'footer_routes': 'Itinéraires populaires',
        'footer_tickets': 'Billets',
        'footer_passes': 'Pass',
        'footer_guides': 'Guides de voyage',
        'footer_contact': 'Contact',
        'footer_copyright': '© 2025 Europe Train. Tous droits réservés.',
    },
    'es': {
        'title': 'Europe Train | Guías de viaje en tren por Europa - Rutas, billetes, pases',
        'description': 'La guía completa para viajar en tren por Europa. Encuentra rutas, compara billetes y descubre los mejores pases.',
        'hero_title': 'Descubre Europa en tren',
        'hero_desc': 'La guía completa para viajar en tren por Europa. Encuentra rutas, compara billetes y descubre los mejores pases.',
        'search_placeholder': 'Buscar destinos, rutas o tipos de trenes...',
        'search_button': 'Buscar',
        'features_title': '¿Por qué viajar en tren?',
        'feature_eco': 'Ecológico',
        'feature_eco_desc': 'Los trenes producen un 90% menos de CO₂ que los aviones. Explora Europa de forma sostenible.',
        'feature_comfort': 'Confort',
        'feature_comfort_desc': 'Asientos espaciosos, coche restaurante, WiFi gratis. Disfruta del viaje.',
        'feature_city': 'Directo al centro',
        'feature_city_desc': 'Sin traslados al aeropuerto. Directo al centro de cada ciudad europea.',
        'feature_price': 'Relación calidad-precio',
        'feature_price_desc': 'Los pases y descuentos de reserva anticipada ahorran dinero. Para todos los presupuestos.',
        'stats_title': 'Datos de viajes en tren por Europa',
        'stats_countries': 'Países cubiertos',
        'stats_network': 'km de red ferroviaria',
        'stats_trains': 'Trenes por día',
        'stats_co2': 'menos CO₂ que el avión',
        'articles_title': 'Últimas guías de viaje',
        'articles_desc': 'Comparaciones profundas, experiencias en tren, conocimiento experto para tu perfecto viaje en tren por Europa',
        'routes_title': 'Rutas populares',
        'routes_link': 'Todas las rutas →',
        'passes_title': 'Pases Eurail & Interrail',
        'passes_desc': 'Viaja flexiblemente por Europa con un pase. 33 países, un billete.',
        'passes_link': 'Comparar pases →',
        'cta_title': '¿Listo para tu viaje en tren por Europa?',
        'cta_desc': 'Encuentra los mejores billetes, rutas y pases para tu viaje perfecto.',
        'cta_button': 'Planificar ahora',
        'footer_desc': 'La guía completa para viajar en tren por Europa.',
        'footer_routes': 'Rutas populares',
        'footer_tickets': 'Billetes',
        'footer_passes': 'Pases',
        'footer_guides': 'Guías de viaje',
        'footer_contact': 'Contacto',
        'footer_copyright': '© 2025 Europe Train. Todos los derechos reservados.',
    },
    'ja': {
        'title': 'Europe Train | ヨーロッパ鉄道旅行ガイド - ルート、切符、パス',
        'description': 'ヨーロッパ鉄道旅行の完全ガイド。ルートを探し、切符を比較し、最適なパスを見つけよう。',
        'hero_title': '鉄道でヨーロッパを旅しよう',
        'hero_desc': 'ヨーロッパ鉄道旅行の完全ガイド。ルートを探し、切符を比較し、最適なパスを見つけよう。',
        'search_placeholder': '目的地、ルート、列車タイプを検索...',
        'search_button': '検索',
        'features_title': 'なぜ鉄道旅行？',
        'feature_eco': 'エコフレンドリー',
        'feature_eco_desc': '列車は飛行機より90%少ないCO₂を排出。持続可能にヨーロッパを探索しよう。',
        'feature_comfort': '快適な体験',
        'feature_comfort_desc': '広い座席、食堂車、無料WiFi。旅を楽しもう。',
        'feature_city': '中心部へダイレクト',
        'feature_city_desc': '空港送迎不要。ヨーロッパの各都市の中心部へダイレクト。',
        'feature_price': 'コスパ良好',
        'feature_price_desc': 'パスと早期割引でお得に。あらゆる予算に対応。',
        'stats_title': 'ヨーロッパ鉄道旅行データ',
        'stats_countries': 'カバー国数',
        'stats_network': 'km鉄道網',
        'stats_trains': '1日の列車本数',
        'stats_co2': '飛行機より少ないCO₂',
        'articles_title': '最新旅行ガイド',
        'articles_desc': '徹底比較、列車体験、専門知識で完璧なヨーロッパ鉄道旅行を計画しよう',
        'routes_title': '人気ルート',
        'routes_link': 'すべてのルート →',
        'passes_title': 'Eurail & Interrail パス',
        'passes_desc': '1枚のパスでヨーロッパを自由に旅しよう。33カ国、1枚の切符。',
        'passes_link': 'パスを比較 →',
        'cta_title': 'ヨーロッパ鉄道旅行の準備はできましたか？',
        'cta_desc': '完璧な旅のための最適な切符、ルート、パスを見つけよう。',
        'cta_button': '今すぐ計画',
        'footer_desc': 'ヨーロッパ鉄道旅行の完全ガイド。',
        'footer_routes': '人気ルート',
        'footer_tickets': '切符',
        'footer_passes': 'パス',
        'footer_guides': '旅行ガイド',
        'footer_contact': 'お問い合わせ',
        'footer_copyright': '© 2025 Europe Train. All rights reserved.',
    },
    'ko': {
        'title': 'Europe Train | 유럽 기차 여행 가이드 - 노선, 티켓, 패스',
        'description': '유럽 기차 여행 완벽 가이드. 노선을 찾고, 티켓을 비교하고, 최적의 패스를 발견하세요.',
        'hero_title': '기차로 유럽을 여행하세요',
        'hero_desc': '유럽 기차 여행 완벽 가이드. 노선을 찾고, 티켓을 비교하고, 최적의 패스를 발견하세요.',
        'search_placeholder': '목적지, 노선 또는 기차 유형 검색...',
        'search_button': '검색',
        'features_title': '왜 기차 여행인가?',
        'feature_eco': '친환경',
        'feature_eco_desc': '기차는 비행기보다 90% 적은 CO₂를 배출합니다. 지속 가능하게 유럽을 탐험하세요.',
        'feature_comfort': '편안함',
        'feature_comfort_desc': '넓은 좌석, 식당차, 무료 WiFi. 여행을 즐기세요.',
        'feature_city': '도심 직행',
        'feature_city_desc': '공항 교통편 필요 없음. 유럽 각 도시의 중심부로 직행.',
        'feature_price': '가성비',
        'feature_price_desc': '패스와 얼리버드 할인으로 돈을 절약하세요. 모든 예산에 맞춤.',
        'stats_title': '유럽 기차 여행 데이터',
        'stats_countries': '커버 국가',
        'stats_network': 'km 철도망',
        'stats_trains': '일일 열차 편수',
        'stats_co2': '비행기보다 적은 CO₂',
        'articles_title': '최신 여행 가이드',
        'articles_desc': '심층 비교, 기차 체험, 전문 지식으로 완벽한 유럽 기차 여행을 계획하세요',
        'routes_title': '인기 노선',
        'routes_link': '모든 노선 →',
        'passes_title': 'Eurail & Interrail 패스',
        'passes_desc': '하나의 패스로 유럽을 자유롭게 여행하세요. 33개국, 하나의 티켓.',
        'passes_link': '패스 비교 →',
        'cta_title': '유럽 기차 여행 준비되셨나요?',
        'cta_desc': '완벽한 여행을 위한 최적의 티켓, 노선, 패스를 찾으세요.',
        'cta_button': '지금 계획하기',
        'footer_desc': '유럽 기차 여행 완벽 가이드.',
        'footer_routes': '인기 노선',
        'footer_tickets': '티켓',
        'footer_passes': '패스',
        'footer_guides': '여행 가이드',
        'footer_contact': '문의하기',
        'footer_copyright': '© 2025 Europe Train. All rights reserved.',
    },
    'pt': {
        'title': 'Europe Train | Guias de viagem de trem na Europa - Rotas, bilhetes, passes',
        'description': 'O guia completo para viajar de trem na Europa. Encontre rotas, compare bilhetes e descubra os melhores passes.',
        'hero_title': 'Descubra a Europa de trem',
        'hero_desc': 'O guia completo para viajar de trem na Europa. Encontre rotas, compare bilhetes e descubra os melhores passes.',
        'search_placeholder': 'Pesquisar destinos, rotas ou tipos de trens...',
        'search_button': 'Pesquisar',
        'features_title': 'Por que viajar de trem?',
        'feature_eco': 'Ecológico',
        'feature_eco_desc': 'Trens produzem 90% menos CO₂ que aviões. Explore a Europa de forma sustentável.',
        'feature_comfort': 'Conforto',
        'feature_comfort_desc': 'Assentos espaçosos, vagão-restaurante, WiFi gratuito. Aproveite a viagem.',
        'feature_city': 'Direto ao centro',
        'feature_city_desc': 'Sem transfers de aeroporto. Direto ao centro de cada cidade europeia.',
        'feature_price': 'Custo-benefício',
        'feature_price_desc': 'Passes e descontos de reserva antecipada economizam dinheiro. Para todos os orçamentos.',
        'stats_title': 'Dados de viagens de trem na Europa',
        'stats_countries': 'Países cobertos',
        'stats_network': 'km de rede ferroviária',
        'stats_trains': 'Trens por dia',
        'stats_co2': 'menos CO₂ que avião',
        'articles_title': 'Últimos guias de viagem',
        'articles_desc': 'Comparações profundas, experiências de trem, conhecimento especializado para sua viagem perfeita de trem na Europa',
        'routes_title': 'Rotas populares',
        'routes_link': 'Todas as rotas →',
        'passes_title': 'Passes Eurail & Interrail',
        'passes_desc': 'Viaje flexivelmente pela Europa com um pass. 33 países, um bilhete.',
        'passes_link': 'Comparar passes →',
        'cta_title': 'Pronto para sua viagem de trem na Europa?',
        'cta_desc': 'Encontre os melhores bilhetes, rotas e passes para sua viagem perfeita.',
        'cta_button': 'Planejar agora',
        'footer_desc': 'O guia completo para viajar de trem na Europa.',
        'footer_routes': 'Rotas populares',
        'footer_tickets': 'Bilhetes',
        'footer_passes': 'Passes',
        'footer_guides': 'Guias de viagem',
        'footer_contact': 'Contato',
        'footer_copyright': '© 2025 Europe Train. Todos os direitos reservados.',
    }
}

def translate_index_html(lang_code):
    """翻译指定语言的首页文件"""
    index_file = os.path.join(BASE_DIR, lang_code, 'index.html')
    
    if not os.path.exists(index_file):
        print(f"✗ 文件不存在: {index_file}")
        return False
    
    with open(index_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    trans = TRANSLATIONS[lang_code]
    
    # 替换内容
    replacements = [
        ('火车游欧洲', trans['hero_title']),
        ('欧洲火车旅行完全指南。查找路线、比较车票、发现最适合的通票。', trans['hero_desc']),
        ('搜索目的地、路线或列车类型...', trans['search_placeholder']),
        ('搜索', trans['search_button']),
        ('为什么选择火车旅行？', trans['features_title']),
        ('🌱 环保出行', f"🌱 {trans['feature_eco']}"),
        ('火车比飞机减少90%碳排放。可持续地探索欧洲，为地球减负。', trans['feature_eco_desc']),
        ('🛋️ 舒适体验', f"🛋️ {trans['feature_comfort']}"),
        ('宽敞座椅、餐车服务、免费WiFi。享受旅途本身，而非忍受旅途。', trans['feature_comfort_desc']),
        ('🏙️ 市中心直达', f"🏙️ {trans['feature_city']}"),
        ('无需机场接送。直达每个欧洲城市的中心，省时省力。', trans['feature_city_desc']),
        ('💰 性价比高', f"💰 {trans['feature_price']}"),
        ('通票和早鸟折扣帮你省钱。各种预算都有选择，灵活出行。', trans['feature_price_desc']),
        ('欧洲火车旅行数据', trans['stats_title']),
        ('欧洲国家覆盖', trans['stats_countries']),
        ('公里铁路网络', trans['stats_network']),
        ('每日列车班次', trans['stats_trains']),
        ('比飞机减少碳排放', trans['stats_co2']),
        ('最新旅行指南', trans['articles_title']),
        ('深度对比、列车体验、硬核科普，助你规划完美欧洲火车之旅', trans['articles_desc']),
        ('热门路线', trans['routes_title']),
        ('所有路线 →', trans['routes_link']),
        ('Eurail & Interrail 通票', trans['passes_title']),
        ('灵活畅游欧洲，一票通行33国。', trans['passes_desc']),
        ('比较通票 →', trans['passes_link']),
        ('准备好开启欧洲火车之旅？', trans['cta_title']),
        ('查找最佳车票、路线和通票，规划你的完美旅程。', trans['cta_desc']),
        ('立即规划', trans['cta_button']),
        ('欧洲火车旅行完全指南', trans['footer_desc']),
        ('热门路线', trans['footer_routes']),
        ('车票', trans['footer_tickets']),
        ('通票', trans['footer_passes']),
        ('旅行指南', trans['footer_guides']),
        ('联系我们', trans['footer_contact']),
        ('© 2025 Europe Train. 保留所有权利。', trans['footer_copyright']),
    ]
    
    for old, new in replacements:
        content = content.replace(old, new)
    
    with open(index_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✓ 已翻译: {index_file}")
    return True

def main():
    print("=" * 60)
    print("翻译 europe-train 多语言站点首页")
    print("=" * 60)
    
    for lang_code in TRANSLATIONS:
        print(f"\n处理语言: {lang_code}")
        translate_index_html(lang_code)
    
    print(f"\n{'=' * 60}")
    print("翻译完成")
    print("=" * 60)

if __name__ == "__main__":
    main()
