#!/usr/bin/env python3
"""
Europe Train - 文章正文批量翻译脚本
为所有非英文文章提供完整的正文翻译
"""

import re
from pathlib import Path

BASE_DIR = Path("/root/.openclaw/workspace/europe-train")

# 通用翻译映射（适用于所有文章）
COMMON_TRANSLATIONS = {
    'de': {
        'Key Information': 'Wichtige Informationen',
        'Key Takeaways': 'Wichtige Punkte',
        'Quick Verdict': 'Schnelles Urteil',
        'Booking Tips': 'Buchungstipps',
        'FAQ': 'Häufige Fragen',
        'Money-Saving Checklist': 'Spar-Checkliste',
        'Main Lines': 'Hauptstrecken',
        'Fare System': 'Tarifsystem',
        'Fare Comparison': 'Tarifvergleich',
        'Seat Selection': 'Sitzplatzwahl',
        'Seat Types': 'Sitzplatztypen',
        'Seat Selection Tips': 'Sitzplatz-Tipps',
        'Download & Register': 'Download & Registrierung',
        'Core Features': 'Kernfunktionen',
        'Route Information': 'Streckeninformation',
        'Best Seats': 'Beste Sitze',
        'Scenery Along the Way': 'Landschaft unterwegs',
        'Onboard Amenities': 'Ausstattung an Bord',
        'Pre-Boarding Ease': 'Komfort vor dem Einsteigen',
        'Dining Car': 'Speisewagen',
        'Scenery': 'Landschaft',
        'Arrival': 'Ankunft',
        'Boarding': 'Einsteigen',
        'Departure': 'Abfahrt',
        'Scope of Application': 'Anwendungsbereich',
        'Basic Rights': 'Grundrechte',
        'Delay Compensation Standards by Country': 'Verspätungsentschädigung nach Land',
        'How Tickets Are Displayed': 'Wie Tickets angezeigt werden',
        'Must validate': 'Muss validiert werden',
        'No validation needed': 'Keine Validierung nötig',
        'Heaviest fines': 'Höchste Strafen',
        'Child policy': 'Kinderpolitik',
        'Tip': 'Tipp',
        'Which Trains Require Reservations?': 'Welche Züge erfordern Reservierungen?',
        'Reservation Fee Comparison': 'Reservierungsgebühren-Vergleich',
        'How to Book Seats': 'Wie man Sitzplätze bucht',
        'Online Booking': 'Online-Buchung',
        'At the Station': 'Am Bahnhof',
        'Seat Classes': 'Sitzplatzklassen',
        'Savings Checklist': 'Spar-Checkliste',
        'App Feature Comparison': 'App-Funktionsvergleich',
        'App Reviews by Country': 'App-Bewertungen nach Land',
        'Pros': 'Vorteile',
        'Cons': 'Nachteile',
        'Special features': 'Besondere Funktionen',
        'Major Train Stations': 'Große Bahnhöfe',
        'Station Facilities': 'Bahnhofseinrichtungen',
        'Common Facilities': 'Allgemeine Einrichtungen',
        'Transfer Tips': 'Umsteigetipps',
        'Same-station transfer': 'Umstieg im selben Bahnhof',
        'Different-station transfer': 'Umstieg in verschiedenen Bahnhöfen',
        'Luggage storage': 'Gepäckaufbewahrung',
        'WiFi': 'WLAN',
        'Charging': 'Laden',
        'Complete Guide': 'Kompletter Guide',
        'Related Guides': 'Verwandte Guides',
        'Read more': 'Mehr lesen',
        'Updated': 'Aktualisiert',
        'All rights reserved': 'Alle Rechte vorbehalten',
    },
    'fr': {
        'Key Information': 'Informations Clés',
        'Key Takeaways': 'Points Clés',
        'Quick Verdict': 'Verdict Rapide',
        'Booking Tips': 'Conseils de Réservation',
        'FAQ': 'FAQ',
        'Money-Saving Checklist': 'Liste de Contrôle Économies',
        'Main Lines': 'Lignes Principales',
        'Fare System': 'Système Tarifaire',
        'Fare Comparison': 'Comparaison des Tarifs',
        'Seat Selection': 'Sélection des Sièges',
        'Seat Types': 'Types de Sièges',
        'Seat Selection Tips': 'Conseils de Sélection de Sièges',
        'Download & Register': 'Télécharger et S\'inscrire',
        'Core Features': 'Fonctionnalités Clés',
        'Route Information': 'Informations sur l\'Itinéraire',
        'Best Seats': 'Meilleurs Sièges',
        'Scenery Along the Way': 'Paysages en Route',
        'Onboard Amenities': 'Équipements à Bord',
        'Pre-Boarding Ease': 'Facilité avant l\'Embarquement',
        'Dining Car': 'Voiture-Restaurant',
        'Scenery': 'Paysage',
        'Arrival': 'Arrivée',
        'Boarding': 'Embarquement',
        'Departure': 'Départ',
        'Scope of Application': 'Champ d\'Application',
        'Basic Rights': 'Droits Fondamentaux',
        'Delay Compensation Standards by Country': 'Normes d\'Indemnisation par Pays',
        'How Tickets Are Displayed': 'Affichage des Billets',
        'Must validate': 'Doit être composté',
        'No validation needed': 'Pas de compostage nécessaire',
        'Heaviest fines': 'Amendes les plus lourdes',
        'Child policy': 'Politique enfant',
        'Tip': 'Conseil',
        'Which Trains Require Reservations?': 'Quels Trains Nécessitent une Réservation?',
        'Reservation Fee Comparison': 'Comparaison des Frais de Réservation',
        'How to Book Seats': 'Comment Réserver des Sièges',
        'Online Booking': 'Réservation en Ligne',
        'At the Station': 'À la Gare',
        'Seat Classes': 'Classes de Sièges',
        'Savings Checklist': 'Liste Économies',
        'App Feature Comparison': 'Comparaison des Fonctionnalités',
        'App Reviews by Country': 'Avis par Pays',
        'Pros': 'Avantages',
        'Cons': 'Inconvénients',
        'Special features': 'Fonctionnalités Spéciales',
        'Major Train Stations': 'Grandes Gares',
        'Station Facilities': 'Équipements de la Gare',
        'Common Facilities': 'Équipements Communs',
        'Transfer Tips': 'Conseils de Correspondance',
        'Same-station transfer': 'Correspondance même gare',
        'Different-station transfer': 'Correspondance gare différente',
        'Luggage storage': 'Consigne',
        'WiFi': 'WiFi',
        'Charging': 'Recharge',
        'Complete Guide': 'Guide Complet',
        'Related Guides': 'Guides Connexes',
        'Read more': 'Lire la suite',
        'Updated': 'Mis à jour',
        'All rights reserved': 'Tous droits réservés',
    },
    'es': {
        'Key Information': 'Información Clave',
        'Key Takeaways': 'Puntos Clave',
        'Quick Verdict': 'Veredicto Rápido',
        'Booking Tips': 'Consejos de Reserva',
        'FAQ': 'Preguntas Frecuentes',
        'Money-Saving Checklist': 'Lista de Ahorro',
        'Main Lines': 'Líneas Principales',
        'Fare System': 'Sistema Tarifario',
        'Fare Comparison': 'Comparación de Tarifas',
        'Seat Selection': 'Selección de Asientos',
        'Seat Types': 'Tipos de Asientos',
        'Seat Selection Tips': 'Consejos de Selección',
        'Download & Register': 'Descargar y Registrarse',
        'Core Features': 'Funciones Principales',
        'Route Information': 'Información de Ruta',
        'Best Seats': 'Mejores Asientos',
        'Scenery Along the Way': 'Paisajes en el Camino',
        'Onboard Amenities': 'Comodidades a Bordo',
        'Pre-Boarding Ease': 'Facilidad antes de Abordar',
        'Dining Car': 'Coche Comedor',
        'Scenery': 'Paisaje',
        'Arrival': 'Llegada',
        'Boarding': 'Embarque',
        'Departure': 'Salida',
        'Scope of Application': 'Ámbito de Aplicación',
        'Basic Rights': 'Derechos Básicos',
        'Delay Compensation Standards by Country': 'Normas de Compensación por País',
        'How Tickets Are Displayed': 'Cómo se Muestran los Billetes',
        'Must validate': 'Debe validarse',
        'No validation needed': 'No necesita validación',
        'Heaviest fines': 'Multas más altas',
        'Child policy': 'Política infantil',
        'Tip': 'Consejo',
        'Which Trains Require Reservations?': '¿Qué Trenes Requieren Reserva?',
        'Reservation Fee Comparison': 'Comparación de Tarifas de Reserva',
        'How to Book Seats': 'Cómo Reservar Asientos',
        'Online Booking': 'Reserva Online',
        'At the Station': 'En la Estación',
        'Seat Classes': 'Clases de Asientos',
        'Savings Checklist': 'Lista de Ahorro',
        'App Feature Comparison': 'Comparación de Funciones',
        'App Reviews by Country': 'Reseñas por País',
        'Pros': 'Ventajas',
        'Cons': 'Desventajas',
        'Special features': 'Funciones Especiales',
        'Major Train Stations': 'Principales Estaciones',
        'Station Facilities': 'Instalaciones de la Estación',
        'Common Facilities': 'Instalaciones Comunes',
        'Transfer Tips': 'Consejos de Transbordo',
        'Same-station transfer': 'Transbordo misma estación',
        'Different-station transfer': 'Transbordo estación diferente',
        'Luggage storage': 'Consigna',
        'WiFi': 'WiFi',
        'Charging': 'Carga',
        'Complete Guide': 'Guía Completa',
        'Related Guides': 'Guías Relacionadas',
        'Read more': 'Leer más',
        'Updated': 'Actualizado',
        'All rights reserved': 'Todos los derechos reservados',
    },
    'ja': {
        'Key Information': '主な情報',
        'Key Takeaways': 'ポイント',
        'Quick Verdict': '結論',
        'Booking Tips': '予約のコツ',
        'FAQ': 'よくある質問',
        'Money-Saving Checklist': '節約チェックリスト',
        'Main Lines': '主要路線',
        'Fare System': '料金システム',
        'Fare Comparison': '料金比較',
        'Seat Selection': '座席選択',
        'Seat Types': '座席タイプ',
        'Seat Selection Tips': '座席選択のコツ',
        'Download & Register': 'ダウンロードと登録',
        'Core Features': '主要機能',
        'Route Information': '路線情報',
        'Best Seats': 'おすすめ座席',
        'Scenery Along the Way': '沿線の景色',
        'Onboard Amenities': '車内設備',
        'Pre-Boarding Ease': '乗車前の便利さ',
        'Dining Car': '食堂車',
        'Scenery': '景色',
        'Arrival': '到着',
        'Boarding': '乗車',
        'Departure': '出発',
        'Scope of Application': '適用範囲',
        'Basic Rights': '基本権利',
        'Delay Compensation Standards by Country': '国別遅延補償基準',
        'How Tickets Are Displayed': 'チケットの表示方法',
        'Must validate': '必須確認',
        'No validation needed': '確認不要',
        'Heaviest fines': '最高罰金',
        'Child policy': '子供政策',
        'Tip': 'ヒント',
        'Which Trains Require Reservations?': '予約が必要な列車は？',
        'Reservation Fee Comparison': '予約料金比較',
        'How to Book Seats': '座席の予約方法',
        'Online Booking': 'オンライン予約',
        'At the Station': '駅で',
        'Seat Classes': '座席クラス',
        'Savings Checklist': '節約チェックリスト',
        'App Feature Comparison': 'アプリ機能比較',
        'App Reviews by Country': '国別アプリレビュー',
        'Pros': 'メリット',
        'Cons': 'デメリット',
        'Special features': '特別機能',
        'Major Train Stations': '主要駅',
        'Station Facilities': '駅の設備',
        'Common Facilities': '共通設備',
        'Transfer Tips': '乗り換えのコツ',
        'Same-station transfer': '同一駅乗り換え',
        'Different-station transfer': '別駅乗り換え',
        'Luggage storage': '荷物預かり',
        'WiFi': 'WiFi',
        'Charging': '充電',
        'Complete Guide': '完全ガイド',
        'Related Guides': '関連ガイド',
        'Read more': '続きを読む',
        'Updated': '更新',
        'All rights reserved': '全著作権所有',
    },
    'ko': {
        'Key Information': '주요 정보',
        'Key Takeaways': '핵심 요약',
        'Quick Verdict': '빠른 결론',
        'Booking Tips': '예약 팁',
        'FAQ': '자주 묻는 질문',
        'Money-Saving Checklist': '절약 체크리스트',
        'Main Lines': '주요 노선',
        'Fare System': '요금 시스템',
        'Fare Comparison': '요금 비교',
        'Seat Selection': '좌석 선택',
        'Seat Types': '좌석 유형',
        'Seat Selection Tips': '좌석 선택 팁',
        'Download & Register': '다운로드 및 등록',
        'Core Features': '핵심 기능',
        'Route Information': '노선 정보',
        'Best Seats': '추천 좌석',
        'Scenery Along the Way': '경치',
        'Onboard Amenities': '차내 편의시설',
        'Pre-Boarding Ease': '탑승 전 편의성',
        'Dining Car': '식당차',
        'Scenery': '경치',
        'Arrival': '도착',
        'Boarding': '탑승',
        'Departure': '출발',
        'Scope of Application': '적용 범위',
        'Basic Rights': '기본 권리',
        'Delay Compensation Standards by Country': '국가별 지연 보상 기준',
        'How Tickets Are Displayed': '티켓 표시 방법',
        'Must validate': '반드시 확인 필요',
        'No validation needed': '확인 불필요',
        'Heaviest fines': '최고 벌금',
        'Child policy': '어린이 정책',
        'Tip': '팁',
        'Which Trains Require Reservations?': '예약이 필요한 열차는?',
        'Reservation Fee Comparison': '예약 수수료 비교',
        'How to Book Seats': '좌석 예약 방법',
        'Online Booking': '온라인 예약',
        'At the Station': '역에서',
        'Seat Classes': '좌석 등급',
        'Savings Checklist': '절약 체크리스트',
        'App Feature Comparison': '앱 기능 비교',
        'App Reviews by Country': '국별 앱 리뷰',
        'Pros': '장점',
        'Cons': '단점',
        'Special features': '특별 기능',
        'Major Train Stations': '주요 역',
        'Station Facilities': '역 시설',
        'Common Facilities': '공통 시설',
        'Transfer Tips': '환승 팁',
        'Same-station transfer': '동일역 환승',
        'Different-station transfer': '다른역 환승',
        'Luggage storage': '수하물 보관',
        'WiFi': 'WiFi',
        'Charging': '충전',
        'Complete Guide': '완벽 가이드',
        'Related Guides': '관련 가이드',
        'Read more': '더 읽기',
        'Updated': '업데이트',
        'All rights reserved': 'All rights reserved',
    },
    'pt': {
        'Key Information': 'Informações Principais',
        'Key Takeaways': 'Pontos Principais',
        'Quick Verdict': 'Veredicto Rápido',
        'Booking Tips': 'Dicas de Reserva',
        'FAQ': 'Perguntas Frequentes',
        'Money-Saving Checklist': 'Lista de Economia',
        'Main Lines': 'Linhas Principais',
        'Fare System': 'Sistema Tarifário',
        'Fare Comparison': 'Comparação de Tarifas',
        'Seat Selection': 'Seleção de Assentos',
        'Seat Types': 'Tipos de Assentos',
        'Seat Selection Tips': 'Dicas de Seleção',
        'Download & Register': 'Download e Registro',
        'Core Features': 'Funcionalidades Principais',
        'Route Information': 'Informações da Rota',
        'Best Seats': 'Melhores Assentos',
        'Scenery Along the Way': 'Paisagens pelo Caminho',
        'Onboard Amenities': 'Comodidades a Bordo',
        'Pre-Boarding Ease': 'Facilidade antes do Embarque',
        'Dining Car': 'Carro Restaurante',
        'Scenery': 'Paisagem',
        'Arrival': 'Chegada',
        'Boarding': 'Embarque',
        'Departure': 'Partida',
        'Scope of Application': 'Âmbito de Aplicação',
        'Basic Rights': 'Direitos Básicos',
        'Delay Compensation Standards by Country': 'Normas de Compensação por País',
        'How Tickets Are Displayed': 'Como os Bilhetes são Exibidos',
        'Must validate': 'Deve validar',
        'No validation needed': 'Sem validação necessária',
        'Heaviest fines': 'Multas mais altas',
        'Child policy': 'Política infantil',
        'Tip': 'Dica',
        'Which Trains Require Reservations?': 'Quais Trens Exigem Reserva?',
        'Reservation Fee Comparison': 'Comparação de Taxas de Reserva',
        'How to Book Seats': 'Como Reservar Assentos',
        'Online Booking': 'Reserva Online',
        'At the Station': 'Na Estação',
        'Seat Classes': 'Classes de Assentos',
        'Savings Checklist': 'Lista de Economia',
        'App Feature Comparison': 'Comparação de Funcionalidades',
        'App Reviews by Country': 'Avaliações por País',
        'Pros': 'Prós',
        'Cons': 'Contras',
        'Special features': 'Funcionalidades Especiais',
        'Major Train Stations': 'Principais Estações',
        'Station Facilities': 'Instalações da Estação',
        'Common Facilities': 'Instalações Comuns',
        'Transfer Tips': 'Dicas de Transbordo',
        'Same-station transfer': 'Transbordo mesma estação',
        'Different-station transfer': 'Transbordo estação diferente',
        'Luggage storage': 'Armazenamento de bagagem',
        'WiFi': 'WiFi',
        'Charging': 'Carregamento',
        'Complete Guide': 'Guia Completo',
        'Related Guides': 'Guias Relacionados',
        'Read more': 'Ler mais',
        'Updated': 'Atualizado',
        'All rights reserved': 'Todos os direitos reservados',
    },
    'it': {
        'Key Information': 'Informazioni Chiave',
        'Key Takeaways': 'Punti Chiave',
        'Quick Verdict': 'Verdetto Rapido',
        'Booking Tips': 'Consigli di Prenotazione',
        'FAQ': 'Domande Frequenti',
        'Money-Saving Checklist': 'Lista Risparmio',
        'Main Lines': 'Linee Principali',
        'Fare System': 'Sistema Tariffario',
        'Fare Comparison': 'Confronto Tariffe',
        'Seat Selection': 'Selezione Posti',
        'Seat Types': 'Tipi di Posti',
        'Seat Selection Tips': 'Consigli Selezione Posti',
        'Download & Register': 'Download e Registrazione',
        'Core Features': 'Funzionalità Principali',
        'Route Information': 'Informazioni Percorso',
        'Best Seats': 'Migliori Posti',
        'Scenery Along the Way': 'Paesaggi Lungo il Percorso',
        'Onboard Amenities': 'Servizi a Bordo',
        'Pre-Boarding Ease': 'Comodità pre-imbarco',
        'Dining Car': 'Vagone Ristorante',
        'Scenery': 'Paesaggio',
        'Arrival': 'Arrivo',
        'Boarding': 'Imbarco',
        'Departure': 'Partenza',
        'Scope of Application': 'Ambito di Applicazione',
        'Basic Rights': 'Diritti Fondamentali',
        'Delay Compensation Standards by Country': 'Standard di Risarcimento per Paese',
        'How Tickets Are Displayed': 'Come sono Visualizzati i Biglietti',
        'Must validate': 'Da convalidare',
        'No validation needed': 'Nessuna convalida necessaria',
        'Heaviest fines': 'Multe più alte',
        'Child policy': 'Politica bambini',
        'Tip': 'Suggerimento',
        'Which Trains Require Reservations?': 'Quali Treni Richiedono Prenotazione?',
        'Reservation Fee Comparison': 'Confronto Tariffe Prenotazione',
        'How to Book Seats': 'Come Prenotare i Posti',
        'Online Booking': 'Prenotazione Online',
        'At the Station': 'In Stazione',
        'Seat Classes': 'Classi di Posti',
        'Savings Checklist': 'Lista Risparmio',
        'App Feature Comparison': 'Confronto Funzionalità App',
        'App Reviews by Country': 'Recensioni per Paese',
        'Pros': 'Pro',
        'Cons': 'Contro',
        'Special features': 'Funzionalità Speciali',
        'Major Train Stations': 'Principali Stazioni',
        'Station Facilities': 'Strutture della Stazione',
        'Common Facilities': 'Strutture Comuni',
        'Transfer Tips': 'Consigli per i Trasferimenti',
        'Same-station transfer': 'Trasferimento stessa stazione',
        'Different-station transfer': 'Trasferimento stazione diversa',
        'Luggage storage': 'Deposito bagagli',
        'WiFi': 'WiFi',
        'Charging': 'Ricarica',
        'Complete Guide': 'Guida Completa',
        'Related Guides': 'Guide Correlate',
        'Read more': 'Leggi di più',
        'Updated': 'Aggiornato',
        'All rights reserved': 'Tutti i diritti riservati',
    },
    'zh': {
        'Key Information': '关键信息',
        'Key Takeaways': '要点总结',
        'Quick Verdict': '快速结论',
        'Booking Tips': '预订技巧',
        'FAQ': '常见问题',
        'Money-Saving Checklist': '省钱清单',
        'Main Lines': '主要线路',
        'Fare System': '票价系统',
        'Fare Comparison': '票价对比',
        'Seat Selection': '座位选择',
        'Seat Types': '座位类型',
        'Seat Selection Tips': '选座技巧',
        'Download & Register': '下载与注册',
        'Core Features': '核心功能',
        'Route Information': '线路信息',
        'Best Seats': '最佳座位',
        'Scenery Along the Way': '沿途风景',
        'Onboard Amenities': '车上设施',
        'Pre-Boarding Ease': '登车前便利',
        'Dining Car': '餐车',
        'Scenery': '风景',
        'Arrival': '到达',
        'Boarding': '登车',
        'Departure': '出发',
        'Scope of Application': '适用范围',
        'Basic Rights': '基本权利',
        'Delay Compensation Standards by Country': '各国延误赔偿标准',
        'How Tickets Are Displayed': '车票显示方式',
        'Must validate': '必须验证',
        'No validation needed': '无需验证',
        'Heaviest fines': '最高罚款',
        'Child policy': '儿童政策',
        'Tip': '提示',
        'Which Trains Require Reservations?': '哪些列车需要预订？',
        'Reservation Fee Comparison': '预订费对比',
        'How to Book Seats': '如何预订座位',
        'Online Booking': '在线预订',
        'At the Station': '在车站',
        'Seat Classes': '座位等级',
        'Savings Checklist': '省钱清单',
        'App Feature Comparison': 'APP功能对比',
        'App Reviews by Country': '各国APP评价',
        'Pros': '优点',
        'Cons': '缺点',
        'Special features': '特色功能',
        'Major Train Stations': '主要火车站',
        'Station Facilities': '车站设施',
        'Common Facilities': '通用设施',
        'Transfer Tips': '换乘提示',
        'Same-station transfer': '同站换乘',
        'Different-station transfer': '异站换乘',
        'Luggage storage': '行李寄存',
        'WiFi': 'WiFi',
        'Charging': '充电',
        'Complete Guide': '完整指南',
        'Related Guides': '相关指南',
        'Read more': '阅读更多',
        'Updated': '更新',
        'All rights reserved': '版权所有',
        # Additional translations
        '1. TGV Network': '1. TGV网络',
        '2. Fare System': '2. 票价系统',
        '3. Booking Tips': '3. 预订技巧',
        '4. Seat Selection': '4. 座位选择',
        '5. SNCF App Guide': '5. SNCF应用指南',
        '1. ICE Route Network': '1. ICE线路网络',
        '2. Fare System': '2. 票价系统',
        '3. BahnCard Membership': '3. BahnCard会员',
        '4. DB Navigator App Guide': '4. DB Navigator应用指南',
        '1. Frecciarossa vs italo Comparison': '1. Frecciarossa与italo对比',
        '2. Fare System': '2. 票价系统',
        '3. Main Routes': '3. 主要线路',
        '4. Seat Classes': '4. 座位等级',
        '1. AVE Route Network': '1. AVE线路网络',
        '2. Fare System': '2. 票价系统',
        '3. Seat Classes': '3. 座位等级',
        '4. Booking Tips': '4. 预订技巧',
        '1. Which Trains Require Reservations?': '1. 哪些列车需要预订？',
        '2. Reservation Fee Comparison': '2. 预订费对比',
        '3. How to Book Seats': '3. 如何预订座位',
        '4. Seat Selection Tips': '4. 选座技巧',
        '5. Eurail Pass Reservation Guide': '5. Eurail通票预订指南',
        '6. Frequently Asked Questions': '6. 常见问题',
        '1. App Feature Comparison': '1. APP功能对比',
        '2. App Reviews by Country': '2. 各国APP评价',
        '1. Major Train Stations': '1. 主要火车站',
        '2. Station Facilities': '2. 车站设施',
        '3. Transfer Tips': '3. 换乘提示',
        '4. Safety Tips': '4. 安全提示',
        '1. Glacier Express': '1. 冰川快车',
        '2. Bernina Express': '2. 伯尔尼纳快车',
        '3. GoldenPass Line': '3. 黄金列车线',
        '4. Other Scenic Trains': '4. 其他景观列车',
        '1. Route Information': '1. 线路信息',
        '2. Fare System': '2. 票价系统',
        '3. Immigration Process': '3. 出入境流程',
        '4. Booking Tips': '4. 预订技巧',
        '1. TGV Lyria Experience in Detail': '1. TGV Lyria体验详情',
        'Boarding: A Sense of Occasion': '登车：仪式感',
        'Departure: From City to Countryside': '出发：从城市到乡村',
        'Dining Car: A Moving French Bistro': '餐车：移动的法式小酒馆',
        'Scenery: Four Seasons in One Journey': '风景：一趟旅程四季变换',
        'Arrival: Seamless Connection': '到达：无缝衔接',
        'Cost & Time Overview': '费用与时间概览',
        'TGV Lyria Experience in Detail': 'TGV Lyria体验详情',
        'Paris to Zurich: Train vs Flight vs Car – In-Depth Comparison': '巴黎到苏黎世：火车 vs 飞机 vs 汽车 – 深度对比',
        'Quick Verdict: Train Wins': '快速结论：火车胜出',
        'Quick Verdict: The Most Pleasant Way to Travel Europe': '快速结论：欧洲最舒适的旅行方式',
        'Pre-Boarding Ease': '登车前便利',
        'Onboard Amenities': '车上设施',
        'Scenery Along the Way': '沿途风景',
        '1. EU Regulation EC 261/2004': '1. 欧盟法规EC 261/2004',
        '2. Delay Compensation Standards by Country': '2. 各国延误赔偿标准',
        'Germany Deutsche Bahn': '德国 Deutsche Bahn',
        'France SNCF': '法国 SNCF',
        'Italy Trenitalia': '意大利 Trenitalia',
        'Switzerland SBB': '瑞士 SBB',
        'Austria ÖBB': '奥地利 ÖBB',
        'Spain Renfe': '西班牙 Renfe',
        'UK National Rail': '英国 National Rail',
        'Netherlands NS': '荷兰 NS',
        'Belgium NMBS/SNCB': '比利时 NMBS/SNCB',
        'Quick Verdict: Rules Vary Widely': '快速结论：规则差异很大',
        'France SNCF: The Most Complex System': '法国SNCF：最复杂的系统',
        'Germany DB: Simple and Flexible': '德国DB：简单灵活',
        'Italy Trenitalia: Validation Required': '意大利Trenitalia：需要验证',
        'Switzerland SBB: Honor System': '瑞士SBB：诚信制度',
        'Spain Renfe: Security Check Required': '西班牙Renfe：需要安检',
        'Austria ÖBB: Similar to Germany': '奥地利ÖBB：与德国类似',
        'UK: No Validation, But Penalty Fares': '英国：无需验证，但有罚款',
        'Netherlands NS: Check-in/Check-out': '荷兰NS：刷卡进出',
        'Belgium NMBS/SNCB: Simple System': '比利时NMBS/SNCB：简单系统',
        'General Tips': '通用提示',
        'Paris, France': '法国巴黎',
        'Berlin, Germany': '德国柏林',
        'Rome, Italy': '意大利罗马',
        'Madrid, Spain': '西班牙马德里',
        'Zurich, Switzerland': '瑞士苏黎世',
        'London, UK': '英国伦敦',
        'Amsterdam, Netherlands': '荷兰阿姆斯特丹',
        'Vienna, Austria': '奥地利维也纳',
        'Brussels, Belgium': '比利时布鲁塞尔',
        'Inter-station Transport in Major Cities': '主要城市车站间交通',
        'Same-station transfer': '同站换乘',
        'Different-station transfer': '异站换乘',
    }
}

def translate_article_content(filepath, lang):
    """翻译单篇文章的正文内容"""
    if lang == 'en':
        return 0
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    translations = COMMON_TRANSLATIONS.get(lang, {})
    
    # 替换所有通用翻译
    for en_text, translated in translations.items():
        # 替换 h2 标题
        content = content.replace(f'<h2>{en_text}</h2>', f'<h2>{translated}</h2>')
        # 替换 h3 标题
        content = content.replace(f'<h3>{en_text}</h3>', f'<h3>{translated}</h3>')
        # 替换 li 中的文本
        content = content.replace(f'<strong>{en_text}:</strong>', f'<strong>{translated}:</strong>')
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return 1
    return 0

def translate_all_articles():
    """批量翻译所有文章"""
    print("🚀 开始批量翻译文章正文...")
    
    total_fixed = 0
    
    for lang in COMMON_TRANSLATIONS.keys():
        lang_dir = BASE_DIR / lang / 'articles'
        if not lang_dir.exists():
            continue
        
        print(f"\n📁 翻译 {lang} 文章...")
        lang_fixed = 0
        
        for article_file in lang_dir.glob('*.html'):
            if article_file.name == 'index.html':
                continue
            if translate_article_content(article_file, lang):
                lang_fixed += 1
                print(f"  ✓ {article_file.name}")
        
        print(f"  ✅ {lang}: {lang_fixed} 篇文章已翻译")
        total_fixed += lang_fixed
    
    print(f"\n✅ 总计: {total_fixed} 篇文章已翻译")

if __name__ == '__main__':
    translate_all_articles()
