#!/usr/bin/env python3
"""
Full dictionary-based translation for all guides files.
Uses pre-defined translations for de/fr/es/ja/ko/pt languages.
"""

import os
import re

# Translation dictionaries for each language
TRANSLATIONS = {
    'de': {
        '20 Popular European Train Routes': '20 Beliebte Europäische Zugstrecken',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': 'Kompletter Guide 2026: Zeiten, Entfernungen, Preise und Buchungstipps',
        'How to Buy European Train Tickets': 'Wie man Europäische Zugtickets kauft',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': 'Kompletter Guide 2026: Offizielle Websites, Frühbucher-Tickets, Preisvergleich',
        'European Rail Pass Guide': 'Europäischer Rail Pass Guide',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': 'Kompletter Guide 2026: Eurail, Interrail, Swiss Travel Pass',
        'European Train Experience Guide': 'Europäischer Zug-Erlebnis-Guide',
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': 'Kompletter Guide 2026: Sitzklassen, Essen, Gepäck, WiFi',
        'Travel Guides': 'Reiseführer',
        'Popular Routes': 'Beliebte Strecken',
        'Tickets': 'Tickets',
        'Passes': 'Pässe',
        'Live Status': 'Live-Status',
        'Home': 'Startseite',
        'Guides': 'Guides',
        'Updated June 2026': 'Aktualisiert Juni 2026',
        'Reading time': 'Lesezeit',
        'minutes': 'Minuten',
        'Key Takeaways': 'Wichtigste Erkenntnisse',
        'Booking Tips': 'Buchungstipps',
        'Related Guides': 'Verwandte Guides',
        'All rights reserved': 'Alle Rechte vorbehalten',
        '1. International Routes': '1. Internationale Strecken',
        '2. France Routes': '2. Strecken in Frankreich',
        '3. Germany Routes': '3. Strecken in Deutschland',
        '4. Italy Routes': '4. Strecken in Italien',
        '5. Scenic Routes': '5. Panoramastrecken',
        'Route': 'Strecke',
        'Time': 'Zeit',
        'Distance': 'Entfernung',
        'Price': 'Preis',
        'Train': 'Zug',
        '1. Official Railway Websites': '1. Offizielle Bahn-Websites',
        '2. Early Bird Ticket Strategies': '2. Frühbucher-Strategien',
        '3. Price Comparison': '3. Preisvergleich',
        '4. Rail Pass vs Point-to-Point': '4. Rail Pass vs Punkt-zu-Punkt',
        '5. Booking Tips by Country': '5. Buchungstipps nach Land',
        'Country': 'Land',
        'Website': 'Website',
        'Early Bird': 'Frühbucher',
        'English': 'Englisch',
        'App': 'App',
        'Money-Saving Checklist': 'Spartipps-Checkliste',
        'When to Choose Rail Pass': 'Wann Rail Pass wählen',
        'When to Choose Point-to-Point': 'Wann Punkt-zu-Punkt wählen',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. Pass-Typen',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. Rentabilitätsanalyse',
        '5. Seat Reservations': '5. Sitzplatzreservierungen',
        'Feature': 'Merkmal',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': 'Berechtigung',
        'Global Pass': 'Global Pass',
        'One Country': 'Ein Land',
        'Adult (1st class)': 'Erwachsene (1. Klasse)',
        'Youth (2nd class)': 'Jugendliche (2. Klasse)',
        'Flexible': 'Flexibel',
        'Continuous': 'Kontinuierlich',
        'Best for': 'Bestens geeignet für',
        'Reservation Checklist': 'Reservierungs-Checkliste',
        'Important Tips': 'Wichtige Tipps',
        '1. Seat Classes Comparison': '1. Sitzklassen-Vergleich',
        '2. Dining Options': '2. Essensmöglichkeiten',
        '3. Luggage Policies': '3. Gepäckrichtlinien',
        '4. WiFi & Power': '4. WiFi & Strom',
        '5. Comfort Tips': '5. Komforttipps',
        'Layout': 'Anordnung',
        'Legroom': 'Beinfreiheit',
        'Power': 'Strom',
        'WiFi': 'WiFi',
        'Meals': 'Mahlzeiten',
        'Quiet': 'Ruhe',
        'Second Class': '2. Klasse',
        'First Class': '1. Klasse',
        'Standard': 'Standard',
        'Extra 15-20cm': 'Extra 15-20cm',
        'Shared per row': 'Geteilt pro Reihe',
        'Individual': 'Individuell',
        'Free (most)': 'Kostenlos (meist)',
        'Free + priority': 'Kostenlos + Priorität',
        'Pay': 'Bezahlen',
        'Included (some)': 'Inklusive (einige)',
        'Quiet cars available': 'Ruhebereiche verfügbar',
        'Base': 'Basis',
        'General Rules': 'Allgemeine Regeln',
        'Storage': 'Aufbewahrung',
        'Tips': 'Tipps',
        'Comfort Checklist': 'Komfort-Checkliste',
    },
    'fr': {
        '20 Popular European Train Routes': '20 Routes Ferroviaires Européennes Populaires',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': 'Guide Complet 2026 : Horaires, distances, prix et conseils',
        'How to Buy European Train Tickets': 'Comment Acheter des Billets de Train Européens',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': 'Guide Complet 2026 : Sites officiels, billets early bird, comparasion',
        'European Rail Pass Guide': 'Guide des Pass Ferroviaires Européens',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': 'Guide Complet 2026 : Eurail, Interrail, Swiss Travel Pass',
        'European Train Experience Guide': "Guide de l'Expérience Train Européen",
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': 'Guide Complet 2026 : Classes de siège, restauration, bagages, WiFi',
        'Travel Guides': 'Guides de Voyage',
        'Popular Routes': 'Routes Populaires',
        'Tickets': 'Billets',
        'Passes': 'Pass',
        'Live Status': 'Statut en Direct',
        'Home': 'Accueil',
        'Guides': 'Guides',
        'Updated June 2026': 'Mis à jour juin 2026',
        'Reading time': 'Temps de lecture',
        'minutes': 'minutes',
        'Key Takeaways': 'Points Clés',
        'Booking Tips': 'Conseils de Réservation',
        'Related Guides': 'Guides Connexes',
        'All rights reserved': 'Tous droits réservés',
        '1. International Routes': '1. Routes Internationales',
        '2. France Routes': '2. Routes en France',
        '3. Germany Routes': '3. Routes en Allemagne',
        '4. Italy Routes': '4. Routes en Italie',
        '5. Scenic Routes': '5. Routes Panoramiques',
        'Route': 'Route',
        'Time': 'Durée',
        'Distance': 'Distance',
        'Price': 'Prix',
        'Train': 'Train',
        '1. Official Railway Websites': '1. Sites Officiels des Chemins de Fer',
        '2. Early Bird Ticket Strategies': '2. Stratégies de Billets Early Bird',
        '3. Price Comparison': '3. Comparaison des Prix',
        '4. Rail Pass vs Point-to-Point': '4. Pass Ferroviaire vs Point-à-Point',
        '5. Booking Tips by Country': '5. Conseils de Réservation par Pays',
        'Country': 'Pays',
        'Website': 'Site Web',
        'Early Bird': 'Early Bird',
        'English': 'Anglais',
        'App': 'App',
        'Money-Saving Checklist': 'Checklist Économies',
        'When to Choose Rail Pass': 'Quand Choisir le Pass Ferroviaire',
        'When to Choose Point-to-Point': 'Quand Choisir Point-à-Point',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. Types de Pass',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. Analyse du Seuil de Rentabilité',
        '5. Seat Reservations': '5. Réservations de Sièges',
        'Feature': 'Caractéristique',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': 'Admissibilité',
        'Global Pass': 'Pass Global',
        'One Country': 'Un Pays',
        'Adult (1st class)': 'Adulte (1ère classe)',
        'Youth (2nd class)': 'Jeune (2ème classe)',
        'Flexible': 'Flexible',
        'Continuous': 'Continu',
        'Best for': 'Idéal pour',
        'Reservation Checklist': 'Checklist de Réservation',
        'Important Tips': 'Conseils Importants',
        '1. Seat Classes Comparison': '1. Comparaison des Classes de Siège',
        '2. Dining Options': '2. Options de Restauration',
        '3. Luggage Policies': '3. Politiques de Bagages',
        '4. WiFi & Power': '4. WiFi & Électricité',
        '5. Comfort Tips': '5. Conseils de Confort',
        'Layout': 'Agencement',
        'Legroom': 'Espace pour les jambes',
        'Power': 'Électricité',
        'WiFi': 'WiFi',
        'Meals': 'Repas',
        'Quiet': 'Calme',
        'Second Class': '2ème classe',
        'First Class': '1ère classe',
        'Standard': 'Standard',
        'Extra 15-20cm': 'Extra 15-20cm',
        'Shared per row': 'Partagé par rangée',
        'Individual': 'Individuel',
        'Free (most)': 'Gratuit (la plupart)',
        'Free + priority': 'Gratuit + priorité',
        'Pay': 'Payant',
        'Included (some)': 'Inclus (certains)',
        'Quiet cars available': 'Voitures calmes disponibles',
        'Base': 'Base',
        'General Rules': 'Règles Générales',
        'Storage': 'Stockage',
        'Tips': 'Conseils',
        'Comfort Checklist': 'Checklist de Confort',
    },
    'es': {
        '20 Popular European Train Routes': '20 Rutas de Tren Europeas Populares',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': 'Guía Completa 2026: Tiempos, distancias, precios y consejos',
        'How to Buy European Train Tickets': 'Cómo Comprar Billetes de Tren Europeos',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': 'Guía Completa 2026: Sitios oficiales, billetes early bird, comparación',
        'European Rail Pass Guide': 'Guía de Pases Ferroviarios Europeos',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': 'Guía Completa 2026: Eurail, Interrail, Swiss Travel Pass',
        'European Train Experience Guide': 'Guía de Experiencia de Tren Europeo',
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': 'Guía Completa 2026: Clases de asiento, comida, equipaje, WiFi',
        'Travel Guides': 'Guías de Viaje',
        'Popular Routes': 'Rutas Populares',
        'Tickets': 'Billetes',
        'Passes': 'Pases',
        'Live Status': 'Estado en Vivo',
        'Home': 'Inicio',
        'Guides': 'Guías',
        'Updated June 2026': 'Actualizado junio 2026',
        'Reading time': 'Tiempo de lectura',
        'minutes': 'minutos',
        'Key Takeaways': 'Puntos Clave',
        'Booking Tips': 'Consejos de Reserva',
        'Related Guides': 'Guías Relacionadas',
        'All rights reserved': 'Todos los derechos reservados',
        '1. International Routes': '1. Rutas Internacionales',
        '2. France Routes': '2. Rutas en Francia',
        '3. Germany Routes': '3. Rutas en Alemania',
        '4. Italy Routes': '4. Rutas en Italia',
        '5. Scenic Routes': '5. Rutas Panorámicas',
        'Route': 'Ruta',
        'Time': 'Tiempo',
        'Distance': 'Distancia',
        'Price': 'Precio',
        'Train': 'Tren',
        '1. Official Railway Websites': '1. Sitios Oficiales de Ferrocarriles',
        '2. Early Bird Ticket Strategies': '2. Estrategias de Billetes Early Bird',
        '3. Price Comparison': '3. Comparación de Precios',
        '4. Rail Pass vs Point-to-Point': '4. Pase Ferroviario vs Punto-a-Punto',
        '5. Booking Tips by Country': '5. Consejos de Reserva por País',
        'Country': 'País',
        'Website': 'Sitio Web',
        'Early Bird': 'Early Bird',
        'English': 'Inglés',
        'App': 'App',
        'Money-Saving Checklist': 'Checklist de Ahorro',
        'When to Choose Rail Pass': 'Cuándo Elegir Pase Ferroviario',
        'When to Choose Point-to-Point': 'Cuándo Elegir Punto-a-Punto',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. Tipos de Pase',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. Análisis del Punto de Equilibrio',
        '5. Seat Reservations': '5. Reservas de Asiento',
        'Feature': 'Característica',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': 'Elegibilidad',
        'Global Pass': 'Pase Global',
        'One Country': 'Un País',
        'Adult (1st class)': 'Adulto (1ª clase)',
        'Youth (2nd class)': 'Joven (2ª clase)',
        'Flexible': 'Flexible',
        'Continuous': 'Continuo',
        'Best for': 'Mejor para',
        'Reservation Checklist': 'Checklist de Reserva',
        'Important Tips': 'Consejos Importantes',
        '1. Seat Classes Comparison': '1. Comparación de Clases de Asiento',
        '2. Dining Options': '2. Opciones de Comida',
        '3. Luggage Policies': '3. Políticas de Equipaje',
        '4. WiFi & Power': '4. WiFi y Electricidad',
        '5. Comfort Tips': '5. Consejos de Confort',
        'Layout': 'Distribución',
        'Legroom': 'Espacio para piernas',
        'Power': 'Electricidad',
        'WiFi': 'WiFi',
        'Meals': 'Comidas',
        'Quiet': 'Silencio',
        'Second Class': '2ª clase',
        'First Class': '1ª clase',
        'Standard': 'Estándar',
        'Extra 15-20cm': 'Extra 15-20cm',
        'Shared per row': 'Compartido por fila',
        'Individual': 'Individual',
        'Free (most)': 'Gratis (la mayoría)',
        'Free + priority': 'Gratis + prioridad',
        'Pay': 'Pago',
        'Included (some)': 'Incluido (algunos)',
        'Quiet cars available': 'Vagones silenciosos disponibles',
        'Base': 'Base',
        'General Rules': 'Reglas Generales',
        'Storage': 'Almacenamiento',
        'Tips': 'Consejos',
        'Comfort Checklist': 'Checklist de Confort',
    },
    'ja': {
        '20 Popular European Train Routes': '人気の欧州鉄道路線20選',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': '2026年完全ガイド：時刻、距離、料金、予約ヒント',
        'How to Buy European Train Tickets': '欧州鉄道切符の購入方法',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': '2026年完全ガイド：公式サイト、早割チケット、料金比較',
        'European Rail Pass Guide': '欧州鉄道パスガイド',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': '2026年完全ガイド：Eurail、Interrail、Swiss Travel Pass',
        'European Train Experience Guide': '欧州鉄道体験ガイド',
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': '2026年完全ガイド：座席クラス、食事、荷物、WiFi',
        'Travel Guides': '旅行ガイド',
        'Popular Routes': '人気ルート',
        'Tickets': '切符',
        'Passes': 'パス',
        'Live Status': 'ライブ状況',
        'Home': 'ホーム',
        'Guides': 'ガイド',
        'Updated June 2026': '2026年6月更新',
        'Reading time': '読了時間',
        'minutes': '分',
        'Key Takeaways': '要点',
        'Booking Tips': '予約のヒント',
        'Related Guides': '関連ガイド',
        'All rights reserved': 'All rights reserved',
        '1. International Routes': '1. 国際ルート',
        '2. France Routes': '2. フランスのルート',
        '3. Germany Routes': '3. ドイツのルート',
        '4. Italy Routes': '4. イタリアのルート',
        '5. Scenic Routes': '5. 景観ルート',
        'Route': 'ルート',
        'Time': '時間',
        'Distance': '距離',
        'Price': '料金',
        'Train': '列車',
        '1. Official Railway Websites': '1. 公式鉄道サイト',
        '2. Early Bird Ticket Strategies': '2. 早割チケット戦略',
        '3. Price Comparison': '3. 料金比較',
        '4. Rail Pass vs Point-to-Point': '4. レールパス vs ポイントトゥポイント',
        '5. Booking Tips by Country': '5. 国別予約ヒント',
        'Country': '国',
        'Website': 'ウェブサイト',
        'Early Bird': '早割',
        'English': '英語',
        'App': 'アプリ',
        'Money-Saving Checklist': '節約チェックリスト',
        'When to Choose Rail Pass': 'レールパスを選ぶ場合',
        'When to Choose Point-to-Point': 'ポイントトゥポイントを選ぶ場合',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. パスタイプ',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. 損益分岐点分析',
        '5. Seat Reservations': '5. 座席予約',
        'Feature': '機能',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': '対象者',
        'Global Pass': 'グローバルパス',
        'One Country': '1カ国',
        'Adult (1st class)': '大人（1等）',
        'Youth (2nd class)': '青年（2等）',
        'Flexible': 'フレキシブル',
        'Continuous': '連続',
        'Best for': '最適な用途',
        'Reservation Checklist': '予約チェックリスト',
        'Important Tips': '重要なヒント',
        '1. Seat Classes Comparison': '1. 座席クラス比較',
        '2. Dining Options': '2. 食事オプション',
        '3. Luggage Policies': '3. 荷物ポリシー',
        '4. WiFi & Power': '4. WiFiと電源',
        '5. Comfort Tips': '5. 快適性のヒント',
        'Layout': '配置',
        'Legroom': '足元スペース',
        'Power': '電源',
        'WiFi': 'WiFi',
        'Meals': '食事',
        'Quiet': '静か',
        'Second Class': '2等',
        'First Class': '1等',
        'Standard': 'スタンダード',
        'Extra 15-20cm': '追加15-20cm',
        'Shared per row': '列ごとに共有',
        'Individual': '個別',
        'Free (most)': '無料（ほとんど）',
        'Free + priority': '無料＋優先',
        'Pay': '有料',
        'Included (some)': '含まれる（一部）',
        'Quiet cars available': '静かな車両あり',
        'Base': '基本',
        'General Rules': '一般ルール',
        'Storage': '収納',
        'Tips': 'ヒント',
        'Comfort Checklist': '快適性チェックリスト',
    },
    'ko': {
        '20 Popular European Train Routes': '인기 유럽 기차 노선 20선',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': '2026년 완벽 가이드: 시간, 거리, 가격, 예약 팁',
        'How to Buy European Train Tickets': '유럽 기차 티켓 구매 방법',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': '2026년 완벽 가이드: 공식 사이트, 얼리버드 티켓, 가격 비교',
        'European Rail Pass Guide': '유럽 철도 패스 가이드',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': '2026년 완벽 가이드: Eurail, Interrail, Swiss Travel Pass',
        'European Train Experience Guide': '유럽 기차 여행 가이드',
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': '2026년 완벽 가이드: 좌석 등급, 식사, 수하물, WiFi',
        'Travel Guides': '여행 가이드',
        'Popular Routes': '인기 경로',
        'Tickets': '티켓',
        'Passes': '패스',
        'Live Status': '실시간 상태',
        'Home': '홈',
        'Guides': '가이드',
        'Updated June 2026': '2026년 6월 업데이트',
        'Reading time': '독서 시간',
        'minutes': '분',
        'Key Takeaways': '핵심 요약',
        'Booking Tips': '예약 팁',
        'Related Guides': '관련 가이드',
        'All rights reserved': 'All rights reserved',
        '1. International Routes': '1. 국제 노선',
        '2. France Routes': '2. 프랑스 노선',
        '3. Germany Routes': '3. 독일 노선',
        '4. Italy Routes': '4. 이탈리아 노선',
        '5. Scenic Routes': '5. 경관 노선',
        'Route': '노선',
        'Time': '시간',
        'Distance': '거리',
        'Price': '가격',
        'Train': '기차',
        '1. Official Railway Websites': '1. 공식 철도 웹사이트',
        '2. Early Bird Ticket Strategies': '2. 얼리버드 티켓 전략',
        '3. Price Comparison': '3. 가격 비교',
        '4. Rail Pass vs Point-to-Point': '4. 레일 패스 vs 포인트 투 포인트',
        '5. Booking Tips by Country': '5. 국가별 예약 팁',
        'Country': '국가',
        'Website': '웹사이트',
        'Early Bird': '얼리버드',
        'English': '영어',
        'App': '앱',
        'Money-Saving Checklist': '비용 절약 체크리스트',
        'When to Choose Rail Pass': '레일 패스를 선택할 때',
        'When to Choose Point-to-Point': '포인트 투 포인트를 선택할 때',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. 패스 유형',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. 손익분기점 분석',
        '5. Seat Reservations': '5. 좌석 예약',
        'Feature': '기능',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': '자격',
        'Global Pass': '글로벌 패스',
        'One Country': '1개국',
        'Adult (1st class)': '성인 (1등석)',
        'Youth (2nd class)': '청소년 (2등석)',
        'Flexible': '유연한',
        'Continuous': '연속',
        'Best for': '최적의 용도',
        'Reservation Checklist': '예약 체크리스트',
        'Important Tips': '중요한 팁',
        '1. Seat Classes Comparison': '1. 좌석 등급 비교',
        '2. Dining Options': '2. 식사 옵션',
        '3. Luggage Policies': '3. 수하물 정책',
        '4. WiFi & Power': '4. WiFi 및 전원',
        '5. Comfort Tips': '5. 편안함 팁',
        'Layout': '배치',
        'Legroom': '다리 공간',
        'Power': '전원',
        'WiFi': 'WiFi',
        'Meals': '식사',
        'Quiet': '조용한',
        'Second Class': '2등석',
        'First Class': '1등석',
        'Standard': '표준',
        'Extra 15-20cm': '추가 15-20cm',
        'Shared per row': '열당 공유',
        'Individual': '개별',
        'Free (most)': '무료 (대부분)',
        'Free + priority': '무료 + 우선',
        'Pay': '유료',
        'Included (some)': '포함 (일부)',
        'Quiet cars available': '조용한 차량 이용 가능',
        'Base': '기본',
        'General Rules': '일반 규칙',
        'Storage': '보관',
        'Tips': '팁',
        'Comfort Checklist': '편안함 체크리스트',
    },
    'pt': {
        '20 Popular European Train Routes': '20 Rotas de Trem Europeias Populares',
        '2026 Complete Guide: Times, distances, prices, and booking tips for classic routes': 'Guia Completo 2026: Horários, distâncias, preços e dicas de reserva',
        'How to Buy European Train Tickets': 'Como Comprar Bilhetes de Trem Europeus',
        '2026 Complete Guide: Official websites, early bird tickets, price comparison, and money-saving tips': 'Guia Completo 2026: Sites oficiais, bilhetes early bird, comparação de preços',
        'European Rail Pass Guide': 'Guia de Passes Ferroviários Europeus',
        '2026 Complete Guide: Eurail, Interrail, Swiss Travel Pass, and country-specific passes': 'Guia Completo 2026: Eurail, Interrail, Swiss Travel Pass',
        'European Train Experience Guide': 'Guia de Experiência de Trem Europeu',
        '2026 Complete Guide: Seat classes, dining, luggage, WiFi, and comfort tips': 'Guia Completo 2026: Classes de assento, refeições, bagagem, WiFi',
        'Travel Guides': 'Guias de Viagem',
        'Popular Routes': 'Rotas Populares',
        'Tickets': 'Bilhetes',
        'Passes': 'Passes',
        'Live Status': 'Status ao Vivo',
        'Home': 'Início',
        'Guides': 'Guias',
        'Updated June 2026': 'Atualizado junho 2026',
        'Reading time': 'Tempo de leitura',
        'minutes': 'minutos',
        'Key Takeaways': 'Pontos Principais',
        'Booking Tips': 'Dicas de Reserva',
        'Related Guides': 'Guias Relacionados',
        'All rights reserved': 'Todos os direitos reservados',
        '1. International Routes': '1. Rotas Internacionais',
        '2. France Routes': '2. Rotas na França',
        '3. Germany Routes': '3. Rotas na Alemanha',
        '4. Italy Routes': '4. Rotas na Itália',
        '5. Scenic Routes': '5. Rotas Panorâmicas',
        'Route': 'Rota',
        'Time': 'Tempo',
        'Distance': 'Distância',
        'Price': 'Preço',
        'Train': 'Trem',
        '1. Official Railway Websites': '1. Sites Oficiais de Ferrovias',
        '2. Early Bird Ticket Strategies': '2. Estratégias de Bilhetes Early Bird',
        '3. Price Comparison': '3. Comparação de Preços',
        '4. Rail Pass vs Point-to-Point': '4. Pass Ferroviário vs Ponto-a-Ponto',
        '5. Booking Tips by Country': '5. Dicas de Reserva por País',
        'Country': 'País',
        'Website': 'Site',
        'Early Bird': 'Early Bird',
        'English': 'Inglês',
        'App': 'App',
        'Money-Saving Checklist': 'Checklist de Economia',
        'When to Choose Rail Pass': 'Quando Escolher Pass Ferroviário',
        'When to Choose Point-to-Point': 'Quando Escolher Ponto-a-Ponto',
        '1. Eurail vs Interrail': '1. Eurail vs Interrail',
        '2. Pass Types': '2. Tipos de Pass',
        '3. Swiss Travel Pass': '3. Swiss Travel Pass',
        '4. Break-Even Analysis': '4. Análise do Ponto de Equilíbrio',
        '5. Seat Reservations': '5. Reservas de Assento',
        'Feature': 'Característica',
        'Eurail': 'Eurail',
        'Interrail': 'Interrail',
        'Eligibility': 'Elegibilidade',
        'Global Pass': 'Pass Global',
        'One Country':